apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcane-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcane-studio
  template:
    metadata:
      labels:
        app: arcane-studio
    spec:
      containers:
      - name: arcane-studio
        image: "arceng/studio:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /healthz/
            port: 8000
          initialDelaySeconds: 5  # Delay before the first probe
          periodSeconds: 10       # How often to perform the probe
        livenessProbe:
          httpGet:
            path: /healthz/
            port: 8000
          initialDelaySeconds: 15  # Delay before the first probe to allow for application startup
          periodSeconds: 20        # How often to perform the probe
        resources:
          limits:
            memory: "500Mi"
            cpu: "1"
          requests:
            memory: "200Mi"
            cpu: "0.2"
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: "studio.settings"
          - name: ROOT_PATH
            value: "/studio"
        envFrom:
          - secretRef:
              name: arcane-studio-secret
